# File: 2020 CN Script.R
# Purpose: Analysis of Florida Canal data generated by the Status 
#  Monitoring Program. Created by Jay Silvanima using code developed 
#  by Tony Olsen, myself, Chris Sedlacek, Stephanie Sunderman-Barnes, 
#  and Liz Miller on 09-26-2020.
# Code developed using R version 3.6.2 (2019-12-12) and spsurvey version
#   4.1.0.

##Set directory. This is where the outputs will be saved. 
#   Alter to desired location. Use getwd() to determine the directory for
#     your r project.

setwd("C:/R/Status 2020/2020 CN")

# First pull data via use of package 'FDEPgetdata'. 

# Load libraries for the data analyses

library(FDEPgetdata)
library(spsurvey)
library(sf)
library(ggplot2)

# Run function of FDEPgetdata package which pull exclusion data.
# 
# Insert varible name between parentheses in function call below.
#
# Insert the name of the exclusion table created in FDEP's Oracle database
#  'GWIS' by Liz Miller. Be sure to enclose table name in single quotes. 

# Example 'CN_EXCLUSIONS_2020'.

FDEPgetdata::getdata_fw_exclusions('CN_EXCLUSIONS_2020')

# Function getdata_fw_exclusions creates a dataframe names 'Exclusions' from the 
#  information provided. Total nitrogen (F.A.C. 62-302.531), total phosphorus (F.A.C. 62-302.531), 
#  and dissolved oxygen (F.A.C. 62-302.533) criteria are added for each record
#  based on the corresponding nutrient watershed region and bioregion.

# Create new data frame from the one just created.

CN.SITES<-Exclusions
names(CN.SITES)

# Convert to Decimal degrees

deg <- floor(CN.SITES$RANDOM_LATITUDE/10000)
min <- floor((CN.SITES$RANDOM_LATITUDE - deg*10000)/100)
sec <- CN.SITES$RANDOM_LATITUDE - deg*10000 - min*100
CN.SITES$latdd <- deg + min/60 + sec/3600
deg <- floor(CN.SITES$RANDOM_LONGITUDE/10000)
min <- floor((CN.SITES$RANDOM_LONGITUDE - deg*10000)/100)
sec <- CN.SITES$RANDOM_LONGITUDE - deg*10000 - min*100
CN.SITES$londd <- deg + min/60 + sec/3600

# Change londd to negative for correct use in sf.
CN.SITES$londd <- -CN.SITES$londd

# Create sf object and transform to Albers projection for analysis
#  This codes utilizes Coordinate Reference System (CRS) Codes.
#  The first crs code below is for NAD 83 Harn datum the second crs code
#  is for Florida albers projection. More information on these codes is found here:
#  https://www.nceas.ucsb.edu/sites/default/files/2020-04/OverviewCoordinateReferenceSystems.pdf.

dsgn_CN <- st_as_sf(CN.SITES, coords = c("londd", "latdd"), remove = FALSE,
                    crs = 4152)
dsgn_sf <- st_transform(dsgn_CN, crs = 3087)

# keep xy coords as variables
tmp <- st_coordinates(dsgn_sf)
dsgn_sf$xcoord <- tmp[, "X"]
dsgn_sf$ycoord <- tmp[, "Y"]

# plot sites using sf
plot(st_geometry(dsgn_sf))

# Site Evaluation
#  The variables CAN_BE_SAMPLED, EXCLUSION_CATEGORY and EXCLUSION_CRITERIA 
#   provide information on the site evaluation results for each site. 
#  Review the information and create target/nontarget (TNT) variable.

addmargins(table(dsgn_sf$EXCLUSION_CATEGORY, dsgn_sf$CAN_BE_SAMPLED, useNA = 'ifany'))
addmargins(table(dsgn_sf$EXCLUSION_CRITERIA, useNA = 'ifany'))


# create sampled and target (T) / nontarget (NT) variables

dsgn_sf$EXCLUSION_CATEGORY <- as.character(dsgn_sf$EXCLUSION_CATEGORY)
dsgn_sf$EXCLUSION_CATEGORY[dsgn_sf$CAN_BE_SAMPLED == 'Y'] <- 'SAMPLED'
dsgn_sf$EXCLUSION_CATEGORY <- as.factor(dsgn_sf$EXCLUSION_CATEGORY)
levels(dsgn_sf$EXCLUSION_CATEGORY)
dsgn_sf$TNT <- dsgn_sf$EXCLUSION_CATEGORY
levels(dsgn_sf$TNT) <- list(T=c('SAMPLED', 'NO PERMISSION FROM OWNER', 'UNABLE TO ACCESS','OTHERWISE UNSAMPLEABLE','DRY'),
                            NT=c('WRONG RESOURCE/NOT PART OF TARGET POPULATION') )

addmargins(table(dsgn_sf$EXCLUSION_CATEGORY, dsgn_sf$TNT, useNA = 'ifany'))

# Adjust weights for Design As Implemented

# Note need frame size here found in design doc for canal site selections
#  Z:\Chris site selection process\2020 site selections\2020 canals\Florida 2020 Canal Design.doc
#  From design document framesize in kilometers = 3921.3123 for entire data frame.

framesize <- c("ZONE 3"=562.7099 ,"ZONE 4"=425.2503 ,
               "ZONE 5"=923.2930 ,"ZONE 6"=2010.0591)

# use all evaluated sites to adjust weights
nr <- nrow(dsgn_sf)
dsgn_sf$wgt <- adjwgt(rep(TRUE,nr), dsgn_sf$NEST1_WT, 
                      dsgn_sf$REPORTING_UNIT, framesize=framesize)

# check sum of weights for each reporting unit/basin
addmargins(tapply(dsgn_sf$wgt, dsgn_sf$REPORTING_UNIT, sum))


# This gives the weights for the canal design as implememented in 2020. 
# It must include all evaluated sites as some sites are not in the 
#  target population.

# Estimate Extent Canal Area.
# Since the sample frame includes portions of canal object line segments that do not 
#  meet the definition of a canal, the site evaluation information is used 
#  to estimate the canal miles in the target population for entire state and for 
#  each of the reporting units/basins.

sites <- data.frame(siteID = dsgn_sf$PK_RANDOM_SAMPLE_LOCATION, Use=rep(TRUE,nr) )
subpop <- data.frame(siteID = dsgn_sf$PK_RANDOM_SAMPLE_LOCATION,
                     Combined = rep("All Basins", nr), 
                     Basin = dsgn_sf$REPORTING_UNIT) 
dsgn <- data.frame(siteID = dsgn_sf$PK_RANDOM_SAMPLE_LOCATION, 
                   wgt = dsgn_sf$wgt,
                   xcoord = dsgn_sf$xcoord,
                   ycoord = dsgn_sf$ycoord,
                   stratum = dsgn_sf$REPORTING_UNIT)

data.cat <- data.frame(siteID = dsgn_sf$PK_RANDOM_SAMPLE_LOCATION,
                       TNTStatus=dsgn_sf$TNT,
                       EXCLUSION.CATEGORY = dsgn_sf$EXCLUSION_CATEGORY)

ExtentEst <- cat.analysis(sites, subpop, dsgn, data.cat, conf=95)

# write out or export results
write.csv(ExtentEst,file = 'ExtentEst.csv')

# Of the 3921.3123 canal miles in the sample frame, 98.99% is estimated to be in the 
#  target population, i.e., 3881.56 miles. Also, only 87.24% of the sample frame 
#  could actually be sampled. To estimate the percent of the target population 
#  that could be sampled, requires that the analysis be restricted to just sites 
#  in the target population, i.e., TNT = "T"

sites <- data.frame(siteID = dsgn_sf$PK_RANDOM_SAMPLE_LOCATION, Use = dsgn_sf$TNT == "T" )
subpop <- data.frame(siteID = dsgn_sf$PK_RANDOM_SAMPLE_LOCATION,
                     Combined = rep("All Basins", nr), 
                     Basin = dsgn_sf$REPORTING_UNIT) 
dsgn <- data.frame(siteID = dsgn_sf$PK_RANDOM_SAMPLE_LOCATION, 
                   wgt = dsgn_sf$wgt,
                   xcoord = dsgn_sf$xcoord,
                   ycoord = dsgn_sf$ycoord,
                   stratum = dsgn_sf$REPORTING_UNIT)

data.cat <- data.frame(siteID = dsgn_sf$PK_RANDOM_SAMPLE_LOCATION,  
                       EXCLUSION.CATEGORY = dsgn_sf$EXCLUSION_CATEGORY)

ExtentEst_Target <- cat.analysis(sites, subpop, dsgn, data.cat, conf=95)

# write out or export results
write.csv(ExtentEst_Target, file = 'ExtentEst_Target.csv')

# 88.13% of the target population area could be sampled, i.e., 
#  3421.02 miles CI(3259.44, 3582.59)miles


#########################################################################################
#########################################################################################
# Water Quality Data

# Run function of FDEPgetdata package to pull result data. 
#
# Insert variable name between parentheses in function call below. The
#  function will pull the water resource for the water resource by year. 
#  For example canal projects during year 2018 the entry would be "'CN18'"
#  Entering "'CN18','CN19','CN20'" for the variable will produce a dataframe for 
#  FDEP Status Canals sampled 2018 - 2020.
#  Be sure to enclose in double and single quotes.
#
# Water resource acronyms are CN = canals, LR = rivers, SS, = Streams.

FDEPgetdata::getdata_results("'CN20'")

# Function getdata_results creates the table 'Results'.

# Create new data frame from the one just created.
CN_RSLTS<-Results
names(CN_RSLTS)

# Determine sample types in file.
addmargins(table(CN_RSLTS$SAMPLE_TYPE, CN_RSLTS$MATRIX, useNA = 'ifany'))

# Note that have BLANK, BOTTOM and PRIMARY data and matrix types. 
# Only want to use PRIMARY results for population estimation.

# Water Quality Analyses
# Water quality analyses are based on 61 sites from the results file and must 
#  be merged with design information. This merge will remove any result data 
#  marked as inappropriate for Status Network analysis (i.e. where 
#  pk_random_sample_location contains "B").

keep <- CN_RSLTS$SAMPLE_TYPE == 'PRIMARY' & CN_RSLTS$MATRIX == 'WATER'

# merge with exclusion file
CN_WQ <- merge(as.data.frame(dsgn_sf)[, c("PK_RANDOM_SAMPLE_LOCATION",
                "REPORTING_UNIT", "EXCLUSION_CATEGORY","TNT", "wgt", 
                "londd", "latdd", "xcoord", "ycoord", "TN_NNC", "TP_NNC",
                "DO_Conc")], CN_RSLTS[keep,], 
               by.x = 'PK_RANDOM_SAMPLE_LOCATION', 
               by.y = 'FK_RANDOM_SAMPLE_LOCATION')

# check that have only PRIMARY for Water MATRIX data
addmargins(table(CN_WQ$SAMPLE_TYPE, CN_WQ$MATRIX, useNA = 'ifany'))

# Note that the number of samples in analysis is now 60. 
#  Sample for Z5-CN-14007B was removed from analysis.


#########################################################################################

########Ammonia Calculation for threshold ####################

## Calculates total ammonia from single sample criteria 

## Code chunk written 1/6/2020 by Stephanie Sunderman Barnes.
## Calculator for total ammonia nitrogen (TAN) single sample criteria.
## Created using TAN calculator spreadsheet as a guide 
## (accessed 1/3/2020, https://floridadep.gov/dear/water-quality-standards-program/documents/total-ammonia-nitrogen-calculator%C2%A0).

##TotAmm.pH = pH used in ammonia calc. If measured pH < 6.5, value used is 6.5. If meas. pH > 9.0, value used is 9.0.
CN_WQ$TotAmm_pH <- ifelse(CN_WQ$pH_Field < 6.5, 6.5, 
                         ifelse(CN_WQ$pH_Field > 9.0, 9.0,CN_WQ$pH_Field))

##TotAmm.temp = water temperature used in ammonia calc. If measured temp < 7 degrees C, value used is 7.
CN_WQ$TotAmm_temp <- ifelse(CN_WQ$Water_Temperature < 7, 7, CN_WQ$Water_Temperature )

##calculate single sample Total Ammonia Criteria using TotAmm.pH and TotAmm.temp							
CN_WQ$TotAmmCrit_SingleSamp <- ifelse(is.na(CN_WQ$TotAmm_pH), NA,
                                     ifelse(is.na(CN_WQ$TotAmm_temp), NA,
                                            (2.5*(0.8876*((0.0278/(1+10^(7.688-CN_WQ$TotAmm_pH)))+(1.1994/(1+10^(CN_WQ$TotAmm_pH-7.688))))*2.126*10^(0.028*(20-(CN_WQ$TotAmm_temp)))))))

##Round result to two decimal places
CN_WQ$TotAmmCrit_SingleSamp <- round(CN_WQ$TotAmmCrit_SingleSamp, digits=2)

##Run analysis similar to NNC using the single sample total ammonia criteria calculated above
### Pass=1 AND Fail=0
CN_WQ$TAmm_Cat<-ifelse((CN_WQ$TotAmmCrit_SingleSamp >= CN_WQ$Ammonia_Total_as_N),1,0)

#########End Ammonia Calculation


#####  Set up threshold category columns for remainder of analytes

#### E_Coli category

E_Coli_cat <- cut(CN_WQ$Escherichia_Coli_Quanti_Tray, breaks=c(0,409,10000000), include.lowest=TRUE)
CN_WQ$E_Coli_cat <- E_Coli_cat
CN_WQ$E_Coli_cat <- as.factor(CN_WQ$E_Coli_cat)

### Old Dissolved Oxygen Category

DO_cat_old <- cut(CN_WQ$Oxygen_Dissolved_Field, breaks=c(0,4.999,1000000), include.lowest=TRUE)
CN_WQ$DO_cat_old <- DO_cat_old
CN_WQ$DO_cat_old <- as.factor(CN_WQ$DO_cat_old)

### pH Category

pH_cat <- cut(CN_WQ$pH_Field, breaks=c(0,5.999,8.5,14), include.lowest=TRUE)
CN_WQ$pH_cat <- pH_cat
CN_WQ$pH_cat <- as.factor(CN_WQ$pH_cat)

### Chlorophyll Category

Chlorophyll_cat <- cut(CN_WQ$Chlorophyll_A_Monochromatic, breaks=c(0,20,10000), include.lowest=TRUE)
CN_WQ$Chlorophyll_cat <- Chlorophyll_cat
CN_WQ$Chlorophyll_cat <- as.factor(CN_WQ$Chlorophyll_cat)

### Calculate Total Nitrogen (TN) as sum of TKN & NO3NO2.
### Numeric Nutrient and DO Categories
### Note Pass=1 AND Fail=0
### Total NNC category = sum of category results for TN, TP, and DO. 
###  If Tot_cat = 3, sample passed criteria for these 3 parameters.


CN_WQ$TN<-(CN_WQ$Kjeldahl_Nitrogen_Total_as_N+CN_WQ$NitrateNitrite_Total_as_N)

CN_WQ$TN_cat<-ifelse((CN_WQ$TN_NNC >= CN_WQ$TN),1,0) 

CN_WQ$TP_cat<-ifelse((CN_WQ$TP_NNC >= CN_WQ$Phosphorus_Total_as_P),1,0)  

CN_WQ$DO_cat<-ifelse((CN_WQ$Oxygen_Dissolved_Percent_Saturation >= CN_WQ$DO_Conc ),1,0)	

CN_WQ$Tot_cat<-(CN_WQ$TN_cat+CN_WQ$TP_cat+CN_WQ$DO_cat)

##### End setting up categories for water quality indicators

##########################################################################
# Continuous and categorical water quality indicator population estimation

nr <- nrow(CN_WQ)
levels(CN_WQ$TNT)

sites_WQ <- data.frame(siteID = CN_WQ$PK_RANDOM_SAMPLE_LOCATION, Use = CN_WQ$TNT == "T" )
subpop_WQ <- data.frame(siteID = CN_WQ$PK_RANDOM_SAMPLE_LOCATION,
                        Combined = rep("All Basins", nrow(CN_WQ)), 
                        Basin = CN_WQ$REPORTING_UNIT) 
dsgn_WQ <- data.frame(siteID = CN_WQ$PK_RANDOM_SAMPLE_LOCATION, 
                      wgt = CN_WQ$wgt,
                      xcoord = CN_WQ$xcoord,
                      ycoord = CN_WQ$ycoord,
                      stratum = CN_WQ$REPORTING_UNIT)

# continuous WQ estimates

data.cont.WQ <- data.frame(siteID=CN_WQ$PK_RANDOM_SAMPLE_LOCATION, 
                           CN_WQ[,c('Oxygen_Dissolved_Field','pH_Field','Escherichia_Coli_Quanti_Tray',
                                    'Chlorophyll_A_Monochromatic','Ammonia_Total_as_N','TN','Phosphorus_Total_as_P')])
Water_quality_Cont <- cont.analysis(sites = sites_WQ, subpop = subpop_WQ, 
                               design = dsgn_WQ, data.cont = data.cont.WQ, conf=95)

# categorical WQ estimates

data.cat.wq <- data.frame(siteID = CN_WQ$PK_RANDOM_SAMPLE_LOCATION,
                           Ammonia_Category = CN_WQ$TAmm_Cat,
                           Chlorophyll_Category = CN_WQ$Chlorophyll_cat,
                           TN_Category = CN_WQ$TN_cat,
                           TP_Category = CN_WQ$TP_cat,
                           DO_Category = CN_WQ$DO_cat,
                           TN_TP_DO_Category = CN_WQ$Tot_cat,
                           E_Coli_Category = CN_WQ$E_Coli_cat,
                           pH_Category = CN_WQ$pH_cat)

Water_Quality_Cat <- cat.analysis(sites = sites_WQ, subpop = subpop_WQ, 
                             design = dsgn_WQ, data.cat = data.cat.wq, conf=95)


# write out the results 
write.csv(Water_Quality_Cat, "2020_CN_Cat.csv")
write.csv(Water_quality_Cont$CDF, file = '2020_CN_Cont_EstCDF.csv')
write.csv(Water_quality_Cont$Pct, file = '2020_CN_Cont_EstPCT.csv')

#### 
#######################################################################################
####
######################################################################################
